version: 2
updates:
  - package-ecosystem: maven
    directory: /fabric-core/fabric-api
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - java

  - package-ecosystem: npm
    directory: /fabric-ui
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    labels:
      - dependencies
      - ci
