-- US002: Template Configuration Enhancement
-- Only missing table needed for template-source field mappings

CREATE TABLE "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" 
(
    "ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
    "FILE_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "TRANSACTION_TYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
    "SOURCE_SYSTEM_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "JOB_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "TARGET_FIELD_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SOURCE_FIELD_NAME" VARCHAR2(100 BYTE),
    "TRANSFORMATION_TYPE" VARCHAR2(20 BYTE) DEFAULT 'source',
    "TRANSFORMATION_CONFIG" VARCHAR2(1000 BYTE), -- JSON config for complex transformations
    "TARGET_POSITION" NUMBER(*,0),
    "LENGTH" NUMBER(*,0),
    "DATA_TYPE" VARCHAR2(20 BYTE),
    "CREATED_BY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CREATED_DATE" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "MODIFIED_BY" VARCHAR2(50 BYTE),
    "MODIFIED_DATE" TIMESTAMP(6),
    "VERSION" NUMBER(*,0) DEFAULT 1,
    "ENABLED" VARCHAR2(1 BYTE) DEFAULT 'Y',
    
    -- Constraints
    CONSTRAINT "PK_TEMPLATE_SOURCE_MAPPINGS" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_TSM_FILE_TYPE" FOREIGN KEY ("FILE_TYPE") 
        REFERENCES "CM3INT"."FILE_TYPE_TEMPLATES" ("FILE_TYPE"),
    CONSTRAINT "FK_TSM_SOURCE_SYSTEM" FOREIGN KEY ("SOURCE_SYSTEM_ID") 
        REFERENCES "CM3INT"."SOURCE_SYSTEMS" ("ID"),
    CONSTRAINT "FK_TSM_FIELD_TEMPLATE" FOREIGN KEY ("FILE_TYPE", "TRANSACTION_TYPE", "TARGET_FIELD_NAME")
        REFERENCES "CM3INT"."FIELD_TEMPLATES" ("FILE_TYPE", "TRANSACTION_TYPE", "FIELD_NAME"),
    
    -- Check constraints
    CHECK ("TRANSFORMATION_TYPE" IN ('source', 'constant', 'formula', 'lookup', 'conditional')),
    CHECK ("ENABLED" IN ('Y', 'N'))
) 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CACS_DATA";

-- Indexes for performance
CREATE INDEX "CM3INT"."IDX_TSM_FILE_TYPE_TRANSACTION" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("FILE_TYPE", "TRANSACTION_TYPE")
    TABLESPACE "CACS_DATA";

CREATE INDEX "CM3INT"."IDX_TSM_SOURCE_SYSTEM" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("SOURCE_SYSTEM_ID")
    TABLESPACE "CACS_DATA";

CREATE INDEX "CM3INT"."IDX_TSM_JOB_NAME" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("JOB_NAME")
    TABLESPACE "CACS_DATA";

CREATE INDEX "CM3INT"."IDX_TSM_ENABLED" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("ENABLED")
    TABLESPACE "CACS_DATA";

-- Unique constraint to prevent duplicate mappings for same template-source-field combination
CREATE UNIQUE INDEX "CM3INT"."UK_TSM_TEMPLATE_SOURCE_FIELD" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("FILE_TYPE", "TRANSACTION_TYPE", "SOURCE_SYSTEM_ID", "TARGET_FIELD_NAME")
    WHERE "ENABLED" = 'Y'
    TABLESPACE "CACS_DATA";

-- Comments for documentation
COMMENT ON TABLE "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" IS 'Stores field-level mappings between templates and source systems for US002 Template Configuration Enhancement';
COMMENT ON COLUMN "CM3INT"."TEMPLATE_SOURCE_MAPPINGS"."FILE_TYPE" IS 'References FILE_TYPE_TEMPLATES.FILE_TYPE';
COMMENT ON COLUMN "CM3INT"."TEMPLATE_SOURCE_MAPPINGS"."TRANSACTION_TYPE" IS 'References FIELD_TEMPLATES.TRANSACTION_TYPE';
COMMENT ON COLUMN "CM3INT"."TEMPLATE_SOURCE_MAPPINGS"."SOURCE_SYSTEM_ID" IS 'References SOURCE_SYSTEMS.ID';
COMMENT ON COLUMN "CM3INT"."TEMPLATE_SOURCE_MAPPINGS"."TARGET_FIELD_NAME" IS 'Template field name from FIELD_TEMPLATES';
COMMENT ON COLUMN "CM3INT"."TEMPLATE_SOURCE_MAPPINGS"."SOURCE_FIELD_NAME" IS 'Source system field name to map from';
COMMENT ON COLUMN "CM3INT"."TEMPLATE_SOURCE_MAPPINGS"."TRANSFORMATION_TYPE" IS 'Type of transformation: source, constant, formula, lookup, conditional';
COMMENT ON COLUMN "CM3INT"."TEMPLATE_SOURCE_MAPPINGS"."TRANSFORMATION_CONFIG" IS 'JSON configuration for complex transformations';