-- US002 End-to-End Testing SQL Script
-- This script sets up the database for comprehensive E2E testing

-- =====================================================
-- E2E-1: CREATE TEMPLATE_SOURCE_MAPPINGS TABLE
-- =====================================================

-- Create the new table for template-source field mappings
CREATE TABLE "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" 
(
    "ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
    "FILE_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "TRANSACTION_TYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
    "SOURCE_SYSTEM_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "JOB_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "TARGET_FIELD_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SOURCE_FIELD_NAME" VARCHAR2(100 BYTE),
    "TRANSFORMATION_TYPE" VARCHAR2(20 BYTE) DEFAULT 'source',
    "TRANSFORMATION_CONFIG" VARCHAR2(1000 BYTE),
    "TARGET_POSITION" NUMBER(*,0),
    "LENGTH" NUMBER(*,0),
    "DATA_TYPE" VARCHAR2(20 BYTE),
    "CREATED_BY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CREATED_DATE" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "MODIFIED_BY" VARCHAR2(50 BYTE),
    "MODIFIED_DATE" TIMESTAMP(6),
    "VERSION" NUMBER(*,0) DEFAULT 1,
    "ENABLED" VARCHAR2(1 BYTE) DEFAULT 'Y',
    
    -- Constraints
    CONSTRAINT "PK_TEMPLATE_SOURCE_MAPPINGS" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_TSM_FILE_TYPE" FOREIGN KEY ("FILE_TYPE") 
        REFERENCES "CM3INT"."FILE_TYPE_TEMPLATES" ("FILE_TYPE"),
    CONSTRAINT "FK_TSM_SOURCE_SYSTEM" FOREIGN KEY ("SOURCE_SYSTEM_ID") 
        REFERENCES "CM3INT"."SOURCE_SYSTEMS" ("ID"),
    CONSTRAINT "FK_TSM_FIELD_TEMPLATE" FOREIGN KEY ("FILE_TYPE", "TRANSACTION_TYPE", "TARGET_FIELD_NAME")
        REFERENCES "CM3INT"."FIELD_TEMPLATES" ("FILE_TYPE", "TRANSACTION_TYPE", "FIELD_NAME"),
    
    -- Check constraints
    CHECK ("TRANSFORMATION_TYPE" IN ('source', 'constant', 'formula', 'lookup', 'conditional')),
    CHECK ("ENABLED" IN ('Y', 'N'))
) 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CACS_DATA";

-- Create indexes for performance
CREATE INDEX "CM3INT"."IDX_TSM_FILE_TYPE_TRANSACTION" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("FILE_TYPE", "TRANSACTION_TYPE")
    TABLESPACE "CACS_DATA";

CREATE INDEX "CM3INT"."IDX_TSM_SOURCE_SYSTEM" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("SOURCE_SYSTEM_ID")
    TABLESPACE "CACS_DATA";

CREATE INDEX "CM3INT"."IDX_TSM_JOB_NAME" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("JOB_NAME")
    TABLESPACE "CACS_DATA";

CREATE INDEX "CM3INT"."IDX_TSM_ENABLED" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("ENABLED")
    TABLESPACE "CACS_DATA";

-- Unique constraint to prevent duplicate mappings
CREATE UNIQUE INDEX "CM3INT"."UK_TSM_TEMPLATE_SOURCE_FIELD" 
    ON "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" ("FILE_TYPE", "TRANSACTION_TYPE", "SOURCE_SYSTEM_ID", "TARGET_FIELD_NAME")
    WHERE "ENABLED" = 'Y'
    TABLESPACE "CACS_DATA";

-- =====================================================
-- E2E TEST DATA SETUP
-- =====================================================

-- Insert sample source systems for testing (if they don't exist)
INSERT INTO "CM3INT"."SOURCE_SYSTEMS" (ID, NAME, TYPE, DESCRIPTION, ENABLED, CREATED_DATE, JOB_COUNT)
SELECT 'HR', 'HR System', 'ORACLE', 'Human Resources management system', 'Y', CURRENT_TIMESTAMP, 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM "CM3INT"."SOURCE_SYSTEMS" WHERE ID = 'HR');

INSERT INTO "CM3INT"."SOURCE_SYSTEMS" (ID, NAME, TYPE, DESCRIPTION, ENABLED, CREATED_DATE, JOB_COUNT)
SELECT 'DDA', 'DDA System', 'ORACLE', 'Deposit Account management system', 'Y', CURRENT_TIMESTAMP, 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM "CM3INT"."SOURCE_SYSTEMS" WHERE ID = 'DDA');

INSERT INTO "CM3INT"."SOURCE_SYSTEMS" (ID, NAME, TYPE, DESCRIPTION, ENABLED, CREATED_DATE, JOB_COUNT)
SELECT 'LOAN', 'Loan System', 'SQLSERVER', 'Loan origination and management system', 'Y', CURRENT_TIMESTAMP, 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM "CM3INT"."SOURCE_SYSTEMS" WHERE ID = 'LOAN');

INSERT INTO "CM3INT"."SOURCE_SYSTEMS" (ID, NAME, TYPE, DESCRIPTION, ENABLED, CREATED_DATE, JOB_COUNT)
SELECT 'CRM', 'CRM System', 'API', 'Customer relationship management system', 'Y', CURRENT_TIMESTAMP, 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM "CM3INT"."SOURCE_SYSTEMS" WHERE ID = 'CRM');

INSERT INTO "CM3INT"."SOURCE_SYSTEMS" (ID, NAME, TYPE, DESCRIPTION, ENABLED, CREATED_DATE, JOB_COUNT)
SELECT 'LEGACY_FILE', 'Legacy File System', 'FILE', 'Legacy flat file processing system', 'Y', CURRENT_TIMESTAMP, 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM "CM3INT"."SOURCE_SYSTEMS" WHERE ID = 'LEGACY_FILE');

-- Insert a disabled system for testing
INSERT INTO "CM3INT"."SOURCE_SYSTEMS" (ID, NAME, TYPE, DESCRIPTION, ENABLED, CREATED_DATE, JOB_COUNT)
SELECT 'OLD_SYSTEM', 'Old System', 'ORACLE', 'Decommissioned legacy system', 'N', CURRENT_TIMESTAMP, 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM "CM3INT"."SOURCE_SYSTEMS" WHERE ID = 'OLD_SYSTEM');

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

-- Verify table creation
SELECT 'TEMPLATE_SOURCE_MAPPINGS table created successfully' as status 
FROM user_tables WHERE table_name = 'TEMPLATE_SOURCE_MAPPINGS';

-- Verify indexes
SELECT index_name, status FROM user_indexes 
WHERE table_name = 'TEMPLATE_SOURCE_MAPPINGS'
ORDER BY index_name;

-- Verify constraints
SELECT constraint_name, constraint_type, status 
FROM user_constraints 
WHERE table_name = 'TEMPLATE_SOURCE_MAPPINGS'
ORDER BY constraint_type, constraint_name;

-- Verify source systems data
SELECT ID, NAME, TYPE, ENABLED, JOB_COUNT, CREATED_DATE 
FROM "CM3INT"."SOURCE_SYSTEMS" 
ORDER BY ENABLED DESC, ID;

-- Verify existing templates for testing
SELECT FILE_TYPE, DESCRIPTION, TOTAL_FIELDS, ENABLED 
FROM "CM3INT"."FILE_TYPE_TEMPLATES" 
WHERE ENABLED = 'Y'
ORDER BY FILE_TYPE;

-- Verify existing field templates for CD01 (if exists)
SELECT FILE_TYPE, TRANSACTION_TYPE, FIELD_NAME, TARGET_POSITION, DATA_TYPE, REQUIRED
FROM "CM3INT"."FIELD_TEMPLATES"
WHERE FILE_TYPE = 'CD01' AND ENABLED = 'Y'
ORDER BY TARGET_POSITION;

-- =====================================================
-- E2E TESTING VALIDATION QUERIES
-- =====================================================

-- Query to check template-source mapping functionality
SELECT 
    tsm.FILE_TYPE,
    tsm.TRANSACTION_TYPE, 
    tsm.SOURCE_SYSTEM_ID,
    ss.NAME as SOURCE_SYSTEM_NAME,
    tsm.JOB_NAME,
    COUNT(tsm.ID) as FIELD_COUNT,
    tsm.CREATED_BY,
    tsm.CREATED_DATE
FROM "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" tsm
LEFT JOIN "CM3INT"."SOURCE_SYSTEMS" ss ON tsm.SOURCE_SYSTEM_ID = ss.ID
WHERE tsm.ENABLED = 'Y'
GROUP BY tsm.FILE_TYPE, tsm.TRANSACTION_TYPE, tsm.SOURCE_SYSTEM_ID, ss.NAME, tsm.JOB_NAME, tsm.CREATED_BY, tsm.CREATED_DATE
ORDER BY tsm.CREATED_DATE DESC;

-- Query to validate field mappings
SELECT 
    tsm.TARGET_FIELD_NAME,
    tsm.SOURCE_FIELD_NAME,
    tsm.TRANSFORMATION_TYPE,
    tsm.TARGET_POSITION,
    tsm.DATA_TYPE,
    ft.REQUIRED as IS_REQUIRED
FROM "CM3INT"."TEMPLATE_SOURCE_MAPPINGS" tsm
LEFT JOIN "CM3INT"."FIELD_TEMPLATES" ft ON 
    tsm.FILE_TYPE = ft.FILE_TYPE AND 
    tsm.TRANSACTION_TYPE = ft.TRANSACTION_TYPE AND 
    tsm.TARGET_FIELD_NAME = ft.FIELD_NAME
WHERE tsm.ENABLED = 'Y'
ORDER BY tsm.FILE_TYPE, tsm.TRANSACTION_TYPE, tsm.SOURCE_SYSTEM_ID, tsm.TARGET_POSITION;

COMMIT;

-- End of E2E Testing Setup Script