spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
    username: cm3int
    password: MySecurePass123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
     maximum-pool-size: 20
     minimum-idle: 1
     auto-commit: false
     connection-timeout: 30000
     idle-timeout: 600000
     max-lifetime: 1800000
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
      table-prefix: CM3INT.BATCH_
    repository:
      incrementer: 
        prefix: CM3INT.

batch:
  gridSize: 10        # number of parallel threads for file partitioning
  chunkSize: 1000    # number of records processed per transaction commit
  defaults:
    inputBasePath:  /data/basepath   # common base path for all sources
    outputBasePath: /Users/pavankanduri/app/software/CACS/ftp/input  # common output base path
    stagingSchema:  CM3INT   # schema where SQL*Loader loads files
    destSchema:     uzcm3ad0   # target schema for Spring Batch reads (was commented out)
    batchDateParam: batch_date  # bind-param name for date filter in queries (was commented out)
    batchDateValue: "#{jobExecutionContext['batchDate']}"  # runtime value for date filter (was commented out)

# Individual source definitions are imported via spring.config.import
# in separate files under src/main/resources/batch-sources/

logging:
  level:
    com.truist.batch: DEBUG
    org.springframework.batch: DEBUG
    org.springframework.boot.context.config: DEBUG