-- Integration Test Database Schema for Manual Job Configuration
-- Oracle Database DDL for US001 Phase 2 Testing

-- Manual Job Configuration Table
CREATE TABLE MANUAL_JOB_CONFIG (
    CONFIG_ID VARCHAR2(50) PRIMARY KEY,
    JOB_NAME VARCHAR2(100) NOT NULL,
    JOB_TYPE VARCHAR2(50) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    TARGET_SYSTEM VARCHAR2(50) NOT NULL,
    JOB_PARAMETERS CLOB,
    DESCRIPTION VARCHAR2(500),
    PRIORITY VARCHAR2(20),
    BUSINESS_JUSTIFICATION VARCHAR2(1000),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR2(100) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(100),
    UPDATED_DATE TIMESTAMP,
    VERSION_NUMBER NUMBER(10) DEFAULT 1,
    CONSTRAINT UK_MANUAL_JOB_CONFIG_NAME UNIQUE (JOB_NAME)
);

-- Manual Job Execution Table
CREATE TABLE MANUAL_JOB_EXECUTION (
    EXECUTION_ID VARCHAR2(50) PRIMARY KEY,
    CONFIG_ID VARCHAR2(50) NOT NULL,
    EXECUTION_STATUS VARCHAR2(20) NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    EXECUTION_PARAMETERS CLOB,
    RESULT_SUMMARY CLOB,
    ERROR_MESSAGE CLOB,
    TRIGGERED_BY VARCHAR2(100) NOT NULL,
    EXECUTION_ENVIRONMENT VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CORRELATION_ID VARCHAR2(36),
    CONSTRAINT FK_EXECUTION_CONFIG FOREIGN KEY (CONFIG_ID) REFERENCES MANUAL_JOB_CONFIG(CONFIG_ID)
);

-- Job Parameter Templates Table
CREATE TABLE JOB_PARAMETER_TEMPLATES (
    TEMPLATE_ID VARCHAR2(50) PRIMARY KEY,
    TEMPLATE_NAME VARCHAR2(100) NOT NULL,
    JOB_TYPE VARCHAR2(50) NOT NULL,
    PARAMETER_SCHEMA CLOB NOT NULL,
    PARAMETER_DEFAULTS CLOB,
    VALIDATION_RULES CLOB,
    DESCRIPTION VARCHAR2(500),
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_BY VARCHAR2(100) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(100),
    UPDATED_DATE TIMESTAMP,
    VERSION_NUMBER NUMBER(10) DEFAULT 1,
    CONSTRAINT UK_PARAMETER_TEMPLATE_NAME UNIQUE (TEMPLATE_NAME)
);

-- Manual Job Audit Table
CREATE TABLE MANUAL_JOB_AUDIT (
    AUDIT_ID VARCHAR2(50) PRIMARY KEY,
    CONFIG_ID VARCHAR2(50),
    EXECUTION_ID VARCHAR2(50),
    AUDIT_ACTION VARCHAR2(50) NOT NULL,
    OLD_VALUES CLOB,
    NEW_VALUES CLOB,
    CHANGED_BY VARCHAR2(100) NOT NULL,
    CHANGED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHANGE_REASON VARCHAR2(500),
    CORRELATION_ID VARCHAR2(36),
    IP_ADDRESS VARCHAR2(45),
    USER_AGENT VARCHAR2(500),
    SESSION_ID VARCHAR2(100)
);

-- Indexes for Performance
CREATE INDEX IDX_MANUAL_JOB_CONFIG_TYPE ON MANUAL_JOB_CONFIG(JOB_TYPE);
CREATE INDEX IDX_MANUAL_JOB_CONFIG_SOURCE ON MANUAL_JOB_CONFIG(SOURCE_SYSTEM);
CREATE INDEX IDX_MANUAL_JOB_CONFIG_STATUS ON MANUAL_JOB_CONFIG(STATUS);
CREATE INDEX IDX_MANUAL_JOB_CONFIG_CREATED ON MANUAL_JOB_CONFIG(CREATED_DATE);

CREATE INDEX IDX_MANUAL_JOB_EXECUTION_CONFIG ON MANUAL_JOB_EXECUTION(CONFIG_ID);
CREATE INDEX IDX_MANUAL_JOB_EXECUTION_STATUS ON MANUAL_JOB_EXECUTION(EXECUTION_STATUS);
CREATE INDEX IDX_MANUAL_JOB_EXECUTION_DATE ON MANUAL_JOB_EXECUTION(CREATED_DATE);

CREATE INDEX IDX_JOB_PARAM_TEMPLATES_TYPE ON JOB_PARAMETER_TEMPLATES(JOB_TYPE);
CREATE INDEX IDX_JOB_PARAM_TEMPLATES_ACTIVE ON JOB_PARAMETER_TEMPLATES(IS_ACTIVE);

CREATE INDEX IDX_MANUAL_JOB_AUDIT_CONFIG ON MANUAL_JOB_AUDIT(CONFIG_ID);
CREATE INDEX IDX_MANUAL_JOB_AUDIT_ACTION ON MANUAL_JOB_AUDIT(AUDIT_ACTION);
CREATE INDEX IDX_MANUAL_JOB_AUDIT_DATE ON MANUAL_JOB_AUDIT(CHANGED_DATE);
CREATE INDEX IDX_MANUAL_JOB_AUDIT_CORRELATION ON MANUAL_JOB_AUDIT(CORRELATION_ID);

-- Test Data for Integration Testing
INSERT INTO JOB_PARAMETER_TEMPLATES (
    TEMPLATE_ID, TEMPLATE_NAME, JOB_TYPE, PARAMETER_SCHEMA, PARAMETER_DEFAULTS, 
    VALIDATION_RULES, DESCRIPTION, CREATED_BY
) VALUES (
    'TPL_ETL_BATCH_001', 'ETL Batch Template', 'ETL_BATCH',
    '{"batchSize": {"type": "number", "required": true}, "connectionTimeout": {"type": "number", "default": 30}}',
    '{"batchSize": 1000, "connectionTimeout": 30, "retryCount": 3}',
    '{"batchSize": {"min": 100, "max": 10000}, "connectionTimeout": {"min": 5, "max": 300}}',
    'Standard ETL batch processing template',
    'system@test.com'
);

INSERT INTO JOB_PARAMETER_TEMPLATES (
    TEMPLATE_ID, TEMPLATE_NAME, JOB_TYPE, PARAMETER_SCHEMA, PARAMETER_DEFAULTS, 
    VALIDATION_RULES, DESCRIPTION, CREATED_BY
) VALUES (
    'TPL_DATA_SYNC_001', 'Data Sync Template', 'DATA_SYNC',
    '{"syncMode": {"type": "string", "required": true}, "incremental": {"type": "boolean", "default": true}}',
    '{"syncMode": "incremental", "incremental": true, "maxRecords": 100000}',
    '{"syncMode": {"values": ["full", "incremental"]}, "maxRecords": {"min": 1000, "max": 1000000}}',
    'Standard data synchronization template',
    'system@test.com'
);

-- Commit the schema changes
COMMIT;