-- H2-compatible schema for integration tests
-- Used by SourceSystemValidationIntegrationTest

CREATE SCHEMA IF NOT EXISTS CM3INT;

-- SOURCE_SYSTEMS table (H2-compatible)
CREATE TABLE IF NOT EXISTS CM3INT.SOURCE_SYSTEMS (
    ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(500),
    CONNECTION_STRING VARCHAR(1000),
    ENABLED VARCHAR(1) DEFAULT 'Y',
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    JOB_COUNT INTEGER DEFAULT 0
);

-- MASTER_QUERY_CONFIG table (H2-compatible, replaces dynamic creation)
CREATE TABLE IF NOT EXISTS MASTER_QUERY_CONFIG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    JOB_NAME VARCHAR(200) NOT NULL,
    QUERY_TEXT CLOB,
    VERSION INTEGER DEFAULT 1,
    IS_ACTIVE VARCHAR(1) DEFAULT 'Y',
    CREATED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(100),
    MODIFIED_DATE TIMESTAMP,
    DESCRIPTION VARCHAR(1000),
    QUERY_TYPE VARCHAR(20) DEFAULT 'SELECT',
    DATA_CLASSIFICATION VARCHAR(50),
    SECURITY_CLASSIFICATION VARCHAR(50),
    BUSINESS_JUSTIFICATION VARCHAR(2000)
);

-- SOURCE_CONFIG table (for DatabasePropertySourceConfig)
CREATE TABLE IF NOT EXISTS SOURCE_CONFIG (
    CONFIG_ID VARCHAR(100) PRIMARY KEY,
    SOURCE_CODE VARCHAR(50),
    CONFIG_KEY VARCHAR(200),
    CONFIG_VALUE VARCHAR(2000),
    DESCRIPTION VARCHAR(500),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR(100),
    ACTIVE VARCHAR(1) DEFAULT 'Y'
);

-- WEBSOCKET_AUDIT_LOG table
CREATE TABLE IF NOT EXISTS WEBSOCKET_AUDIT_LOG (
    AUDIT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_SUBTYPE VARCHAR(50),
    EVENT_DESCRIPTION VARCHAR(500),
    SESSION_ID VARCHAR(100),
    USER_ID VARCHAR(100),
    CLIENT_IP VARCHAR(50),
    USER_AGENT VARCHAR(500),
    ORIGIN_URL VARCHAR(200),
    EVENT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SECURITY_EVENT_FLAG VARCHAR(1) DEFAULT 'N',
    COMPLIANCE_EVENT_FLAG VARCHAR(1) DEFAULT 'N',
    EVENT_SEVERITY VARCHAR(20),
    RISK_LEVEL VARCHAR(20),
    BUSINESS_FUNCTION VARCHAR(100),
    CORRELATION_ID VARCHAR(100),
    AUDIT_HASH VARCHAR(256),
    PREVIOUS_AUDIT_HASH VARCHAR(256),
    DIGITAL_SIGNATURE VARCHAR(1000),
    SECURITY_CLASSIFICATION VARCHAR(50),
    SOURCE_SYSTEM VARCHAR(100),
    THREAD_ID VARCHAR(100),
    SERVER_HOSTNAME VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DASHBOARD_METRICS_TIMESERIES table
CREATE TABLE IF NOT EXISTS DASHBOARD_METRICS_TIMESERIES (
    METRICS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EXECUTION_ID VARCHAR(100),
    METRIC_NAME VARCHAR(100),
    METRIC_TYPE VARCHAR(50),
    METRIC_VALUE DECIMAL(19,4),
    METRIC_UNIT VARCHAR(20),
    METRIC_STATUS VARCHAR(20),
    METRIC_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CPU_USAGE_PERCENT DECIMAL(5,2),
    MEMORY_USAGE_MB BIGINT,
    PROCESSING_DURATION_MS BIGINT,
    THROUGHPUT_PER_SECOND DECIMAL(19,4),
    SUCCESS_RATE_PERCENT DECIMAL(5,2),
    CORRELATION_ID VARCHAR(100),
    SOURCE_SYSTEM VARCHAR(100),
    USER_ID VARCHAR(100),
    THREAD_ID VARCHAR(100),
    AUDIT_HASH VARCHAR(256),
    COMPLIANCE_FLAGS VARCHAR(500),
    SECURITY_CLASSIFICATION VARCHAR(50),
    DATA_QUALITY_SCORE DECIMAL(5,2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PARTITION_ID VARCHAR(50)
);
