# ======================================
# FABRIC PLATFORM - DEVELOPMENT PROFILE
# ======================================
# Local development environment configuration
# Uses local Oracle database with relaxed security settings

spring:
  profiles:
    active: dev 
  # Database Configuration - Oracle Local
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521:XE}
    username: ${DB_USERNAME:fabric_dev}
    password: ${DB_PASSWORD:fabric_dev_pass}
    driver-class-name: oracle.jdbc.OracleDriver
    
    # Connection Pool Settings (Development)
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      leak-detection-threshold: 60000
      pool-name: FabricDevPool
  mvc:
    cors:
      mappings:
        allowed-origins: "http://localhost:3000"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
        allow-credentials: true
     

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Redis Configuration (Local)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Fabric Platform Configuration
fabric:
  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:fabric-dev-jwt-secret-key-minimum-256-bits-required-for-hmac-sha-development}
      access-token-expiration: 900  # 15 minutes
      refresh-token-expiration: 28800  # 8 hours
      issuer: fabric-platform-dev
      audience: fabric-users-dev
    cors:
      allowed-origins: http://localhost:3000,https://localhost:3000,http://localhost:3001
    csrf:
      enabled: false  # Disabled for development

  # Data Loading Configuration
  data-loader:
    batch-size: 1000
    chunk-size: 100
    max-threads: 4
    error-threshold: 0.05  # 5% error threshold
    temp-directory: ${TEMP_DIR:/tmp/fabric-dev}
    
  # SQL*Loader Configuration
  sql-loader:
    oracle-home: ${ORACLE_HOME:/opt/oracle/instantclient}
    control-file-template: pipe-delimited-control-template.ctl
    parallel-degree: 2
    
  # File Processing
  file-processing:
    input-directory: ${INPUT_DIR:./data/input}
    output-directory: ${OUTPUT_DIR:./data/output}
    archive-directory: ${ARCHIVE_DIR:./data/archive}
    error-directory: ${ERROR_DIR:./data/error}

# Logging Configuration
logging:
  level:
    com.truist.batch: DEBUG
    org.springframework.security: DEBUG
    org.springframework.batch: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-}] %logger{50} - %msg%n"
  file:
    name: ./logs/fabric-dev.log

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,configprops,env
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
        
        # Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
  http2:
    enabled: true